language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - valgrind
            - libcppunit-dev
      env: COMPILER=g++-4.9
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - valgrind
            - libcppunit-dev
      env: COMPILER=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - libcppunit-dev
      env: COMPILER=g++-6
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - valgrind
            - libcppunit-dev
      env: COMPILER=g++-7
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-3.6
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-3.7
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-3.8
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-3.9
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-4.0
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - valgrind
            - libcppunit-dev
      env: COMPILER=clang++-5.0
    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env: COMPILER=g++-4.9
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: COMPILER=clang++

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      if [ "${COMPILER}" = "g++-4.9" ]; then
        brew install valgrind;
        HOMEBREW_CC=gcc-4.9 HOMEBREW_CXX=g++-4.9 brew install --build-from-source cppunit;
      elif [ "${COMPILER}" = "clang++" ]; then
        brew install valgrind cppunit;
      fi;
    fi;
before_script: mkdir build && cd build
script:
  - export CXX=${COMPILER}
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEOMETRY_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -pedantic" .. && make && ctest --verbose -D ExperimentalMemCheck
