version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake -G "%CMAKE_GENERATOR%" -DGEOMETRY_BUILD_TESTS=OFF ..

    cd ..
build:
  verbosity: normal
